# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2048M

# Mod properties
mod_version=1.5.3
maven_group=net.satisfy
archives_base_name=vinery
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=26.2

# Dependencies
architectury_version=21.1.8
rei_version=26.2.820
jei_version=30.32.0.211
cloth_fabric_version=26.2.155
mod_menu_version=20.0.1
fabric_loader_version=0.16.10
fabric_api_version=0.160.0+26.2
neo_forge_version=26.2.0.83
